"""Add razorpay fields to user

Revision ID: 097456bffe2d
Revises: 88a453887a18
Create Date: 2026-01-02 18:12:25.089065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097456bffe2d'
down_revision: Union[str, Sequence[str], None] = '88a453887a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'razorpay_payment_id')
    op.drop_column('users', 'razorpay_order_id')
    # ### end Alembic commands ###
