"""Add user profile fields and subscription tier

Revision ID: 98594c40cae5
Revises: 
Create Date: 2026-01-02 17:50:45.683266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98594c40cae5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('blood_group', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'blood_group')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    # ### end Alembic commands ###
