"""Add transaction_id to user

Revision ID: c89882791853
Revises: 98594c40cae5
Create Date: 2026-01-02 17:59:36.771856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89882791853'
down_revision: Union[str, Sequence[str], None] = '98594c40cae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transaction_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transaction_id')
    # ### end Alembic commands ###
